# Generated by Django 5.0.6 on 2024-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
